name = "website-archiver"
workers_dev = true

[vars]
ARCHIVER_KEY = "your-secret-key"
STATIC_URL = "https://your-domain.com"

[[r2_buckets]]
binding = "ARCHIVE_BUCKET"
bucket_name = "your-bucket-name"
preview_bucket_name = "your-bucket-name-preview"